export enum RequestType {
  BORROW = 'EMPRESTAR',
  TASK = 'TAREFA',
  COMPANY = 'COMPANHIA',
  URGENCY = 'URGÊNCIA',
}

export enum AppScreen {
  FEED = 'FEED',
  CREATE = 'CREATE',
  PROFILE = 'PROFILE',
  COMMUNITY = 'COMMUNITY'
}

export interface UserReputation {
  reliability: number; // 0-5
  speed: number; // 0-5
  kindness: number; // 0-5
  totalFavors: number;
}

export interface UserLocation {
  neighborhood: string;
  city: string;
  state: string;
  country: string;
}

export interface User {
  id: string;
  email?: string; // Novo campo para autenticação real
  name: string;
  avatar: string;
  reputation: UserReputation;
  location: UserLocation;
  distance: string; // Pre-calculated string for UI relative distance
}

export interface HelpRequest {
  id: string;
  userId: string;
  user: User;
  type: RequestType;
  title: string;
  description: string;
  timestamp: number;
  status: 'OPEN' | 'IN_PROGRESS' | 'COMPLETED';
  locationLabel: string;
  aiSafetyTip?: string; // Generated by Gemini
}

export interface AIEnhancementResult {
  improvedText: string;
  safetyTip: string;
  encouragement: string;
}

export interface AppNotification {
  id?: string;
  toUserId: string;
  fromUserId: string;
  fromUserName: string;
  message: string;
  requestId?: string;
  read: boolean;
  timestamp: number;
}